/* eslint-disable no-underscore-dangle */
// Stage 5 "Generated Assets" panel (ticket #61, FR-42 / FR-43).
//
// The left-hand card of Stage 5: the grid of Firefly assets beside the page. It
// composes the three Stage 5 seams and owns none of their work:
//   - asset-generation.js (#59) reads the page doc back from DA, finds the
//     placeholder slots, and generates the images in ONE AO turn.
//   - asset-swap.js (#60) gives every image a permanent DA home, rewrites only
//     the `<img src>` values, and re-previews the page once.
//   - stage-state.js `saveAssets` (#58) merges the rows into the project record
//     by `slot`, so a Regenerate replaces exactly one row.
//
// On open, when the project has no assets yet, it generates the whole page in
// one turn (mirrors page-preview-panel.js:92); afterwards each card regenerates
// on its own. The page is written by the sibling Stage 4 panel, so it can
// arrive after this panel is on screen - the auto-run therefore also fires when
// a `page` shows up, the same way preflight-panel.js waits for its audit URL.
//
// The panel never blocks. `generateAssets`, `swapAssetsIntoPage` and every seam
// under them return soft errors instead of throwing, so a slot that failed
// simply keeps its placeholder and carries its own note while the other slots
// land. Both stored URLs can fail on their own terms too - the Firefly
// `sourceUrl` expires after an hour and the DA `mediaUrl` is auth-protected -
// so a card walks `thumbnailCandidates` on an image error and ends at the
// placeholder rather than showing a broken image.
//
// Output: `assets-changed` after every persisted change, so the sibling detail
// view (#62) and the Assets Rendering preview (#63) can react; `asset-selected`
// when a card asks for its detail. Wiring those together is the shell's job
// (#64) - this component stays standalone.

import { LitElement, html } from 'da-lit';
import {
  readPageDoc, extractSlots, generateAssets, generateAsset,
} from './asset-generation.js';
import { swapAssetsIntoPage } from './asset-swap.js';
import { saveAssets } from './stage-state.js';
import {
  FIREFLY_URL, pagePath, assetRow, assetRecord, mergeAssets, gridRows, assetCount,
  slotJobs, swappableAssets,
} from './assets-logic.js';

class DaAssetsPanel extends LitElement {
  static properties = {
    context: { attribute: false },
    daFetch: { attribute: false },
    slug: { attribute: false },
    page: { attribute: false },
    creativeDirection: { attribute: false },
    assets: { attribute: false },
    _assets: { state: true },
    _slots: { state: true },
    _busy: { state: true },
    _reading: { state: true },
    _fallbacks: { state: true },
    _note: { state: true },
    _error: { state: true },
  };

  constructor() {
    super();
    this.context = null;
    this.daFetch = null;
    this.slug = null;
    this.page = null;
    this.creativeDirection = null;
    this.assets = null;
    this._assets = [];
    this._slots = [];
    this._busy = [];
    this._reading = false;
    // Per slot: how far down `thumbnailCandidates` that card has had to walk.
    this._fallbacks = {};
    this._note = '';
    this._error = null;
    this._ran = false;
  }

  createRenderRoot() {
    return this;
  }

  firstUpdated() {
    this._assets = Array.isArray(this.assets) ? this.assets : [];
    // Auto-generate only when the project has no assets; saved assets open as-is
    // and Regenerate re-runs one slot.
    this.maybeGenerate();
  }

  // The page is generated by Stage 4, so it can land after this panel is on
  // screen: start as soon as a page shows up. The owner's rows can also change
  // under the panel - the detail view (#62) regenerates one slot and the shell
  // hands the merged list back (#64) - so take those in too, except while a run
  // of our own is in flight, which owns the rows it is writing.
  updated(changed) {
    if (changed.has('page')) this.maybeGenerate();
    if (changed.has('assets') && !this._busy.length) {
      this._assets = mergeAssets(this._assets, this.assets);
    }
  }

  maybeGenerate() {
    if (this._ran || this._busy.length || this._assets.length) return;
    if (!pagePath(this.page)) return;
    this._ran = true;
    this.generateAll();
  }

  get target() {
    return { org: this.context?.org, site: this.context?.repo };
  }

  // The page doc is the source of truth for the image slots: Stage 4 persists
  // no outline, so every run reads it back from DA first.
  async loadSlots() {
    const { org, site } = this.target;
    this._reading = true;
    try {
      const { html: doc, error } = await readPageDoc(this.daFetch, org, site, pagePath(this.page));
      if (error) {
        this._error = error;
        return [];
      }
      const slots = extractSlots(doc);
      this._slots = slots;
      return slots;
    } finally {
      this._reading = false;
    }
  }

  /**
   * Generate every empty slot of the page in ONE AO turn - N slots cost about
   * as much as one, because AO batches the Firefly calls (gate #57).
   */
  async generateAll() {
    this._error = null;
    this._note = '';
    const slots = await this.loadSlots();
    if (!slots.length) {
      if (!this._error) this._note = 'This page has no placeholder images to generate.';
      return;
    }
    this._busy = slots.map((s) => s.slot);
    try {
      const results = await generateAssets(this.context, slotJobs(slots, this.creativeDirection));
      const bySlot = new Map(slots.map((s) => [s.slot, s]));
      const rows = results.map((r) => assetRow(r, bySlot.get(r.slot), this.creativeDirection));
      await this.persist(rows);
      await this.swap(rows);
    } finally {
      this._busy = [];
    }
  }

  /**
   * Regenerate ONE slot: the single-slot case of the same loop, which replaces
   * exactly that card, that DA asset and that row in the assets sheet.
   * @param {{slot: number, alt?: string, aspect?: string}} card
   */
  async regenerate(card) {
    const slot = Number(card?.slot);
    if (!Number.isFinite(slot) || this._busy.includes(slot)) return;
    this._error = null;
    this._note = '';
    this._busy = [...this._busy, slot];
    this._fallbacks = { ...this._fallbacks, [slot]: 0 };
    try {
      const [job] = slotJobs([card], this.creativeDirection);
      const result = await generateAsset(this.context, job);
      const row = assetRow(result, card, this.creativeDirection);
      await this.persist([row]);
      await this.swap([row]);
    } finally {
      this._busy = this._busy.filter((s) => s !== slot);
    }
  }

  /**
   * Record the generated rows before the swap touches the page, so a swap that
   * fails cannot lose a generation that succeeded. `saveAssets` merges by slot,
   * so a concurrent write is not clobbered.
   */
  async persist(rows) {
    this._assets = mergeAssets(this._assets, rows);
    try {
      await saveAssets(this.context, this.daFetch, this.slug, {
        assets: rows.map(assetRecord),
      });
      this.announce();
    } catch (e) {
      this._error = `The assets were generated, but not saved: ${e.message || 'unknown error'}`;
    }
  }

  /**
   * Put the generated images into the page: permanent DA copies, only the
   * `<img src>` values rewritten, one re-preview for the whole page, and the
   * `mediaUrl` back into the assets sheet (#60). Never throws; a slot that
   * could not be swapped keeps its placeholder and its own note.
   */
  async swap(rows) {
    const generated = swappableAssets(rows);
    if (!generated.length) return;
    const result = await swapAssetsIntoPage(this.context, this.daFetch, {
      slug: this.slug,
      path: pagePath(this.page),
      assets: generated.map(assetRecord),
    });
    if (result.assets?.length) {
      // The swap rows carry `mediaUrl`, but only the sheet columns: keep what
      // the generation knew about each slot underneath them.
      const merged = result.assets.map((row) => ({
        ...generated.find((r) => Number(r.slot) === Number(row.slot)),
        ...row,
      }));
      this._assets = mergeAssets(this._assets, merged);
      this.announce();
    }
    if (result.error) this._error = result.error;
  }

  // Tell the shell what the project's assets now are, so the detail view (#62)
  // and the rendering preview (#63) see the same rows without re-reading DA.
  announce() {
    this.dispatchEvent(new CustomEvent('assets-changed', {
      detail: { assets: this._assets.map(assetRecord) },
      bubbles: true,
      composed: true,
    }));
  }

  // A card asks for its detail view. The view itself is a sibling ticket (#62)
  // and the wiring is the shell's (#64); the panel only says which asset.
  select(card) {
    this.dispatchEvent(new CustomEvent('asset-selected', {
      detail: { asset: assetRecord(card) },
      bubbles: true,
      composed: true,
    }));
  }

  // Walk to the next candidate URL for a card whose image would not load. The
  // last candidate is the slot's placeholder, which always renders.
  onImageError(card) {
    const next = (this._fallbacks[card.slot] || 0) + 1;
    if (next >= card.thumbnails.length) return;
    this._fallbacks = { ...this._fallbacks, [card.slot]: next };
  }

  thumbnail(card) {
    const index = Math.min(this._fallbacks[card.slot] || 0, card.thumbnails.length - 1);
    return card.thumbnails[index] || '';
  }

  get cards() {
    return gridRows(this._slots, this._assets, this._busy);
  }

  renderThumb(card) {
    if (card.state === 'generating') {
      return html`<div class="cw-as-thumb is-busy" role="img"
        aria-label="Generating ${card.label}"><span class="cw-as-spinner"></span></div>`;
    }
    const src = this.thumbnail(card);
    if (!src) return html`<div class="cw-as-thumb is-empty"><span class="cw-muted">No image</span></div>`;
    return html`<div class="cw-as-thumb">
      <img class="cw-as-img" src=${src} alt=${card.alt || card.label} loading="lazy"
        @error=${() => this.onImageError(card)}>
    </div>`;
  }

  // The per-asset overflow menu. A <details> so the disclosure is keyboard
  // accessible for free - the same trick preflight-panel.js uses for its rows.
  renderMenu(card) {
    const file = this.thumbnail(card);
    const busy = card.state === 'generating';
    return html`
      <details class="cw-as-menu">
        <summary class="cw-as-menu-btn" title="Asset actions"
          aria-label="Actions for ${card.label}">...</summary>
        <div class="cw-as-menu-list" role="menu">
          <button class="cw-as-menu-item" role="menuitem" ?disabled=${busy}
            @click=${() => this.regenerate(card)}>Regenerate</button>
          <button class="cw-as-menu-item" role="menuitem"
            @click=${() => this.select(card)}>View details</button>
          ${file ? html`<a class="cw-as-menu-item" role="menuitem" href=${file}
            download target="_blank" rel="noopener">Download</a>` : ''}
        </div>
      </details>`;
  }

  renderCard(card) {
    return html`
      <li class="cw-as-card is-${card.state}" aria-busy=${card.state === 'generating'}>
        ${this.renderThumb(card)}
        <div class="cw-as-foot">
          <span class="cw-as-label" title=${card.label}>${card.label}</span>
          ${this.renderMenu(card)}
        </div>
        ${card.state === 'failed' ? html`<p class="cw-as-note">
          ${card.error || 'This image could not be generated. The page keeps its placeholder.'}
        </p>` : ''}
      </li>`;
  }

  renderBody() {
    if (!pagePath(this.page)) {
      return html`<p class="cw-muted">
        No page yet. The assets follow the page's image slots, so generate the page first.</p>`;
    }
    const { cards } = this;
    if (!cards.length) {
      return html`<p class="cw-muted">
        ${this._reading ? 'Reading the page...' : this._note || 'No image slots yet.'}</p>`;
    }
    return html`
      <ul class="cw-as-grid">${cards.map((card) => this.renderCard(card))}</ul>
      ${this._note ? html`<p class="cw-muted cw-as-panel-note">${this._note}</p>` : ''}`;
  }

  render() {
    const { label } = assetCount(this.cards);
    const running = this._busy.length > 0;
    return html`
      <div class="cw-cn-header">
        <h3 class="cw-kw-title">Generated Assets</h3>
        <div class="cw-as-actions">
          <span class="cw-as-count">${label}</span>
          <a class="nx-action-btn nx-btn-sm" href=${FIREFLY_URL}
            target="_blank" rel="noopener">Go to Firefly</a>
        </div>
      </div>
      ${running ? html`<p class="cw-muted">Generating the images with Firefly...</p>` : ''}
      ${this.renderBody()}
      ${this._error ? html`<p class="cw-error">${this._error}</p>` : ''}`;
  }
}

customElements.define('da-assets-panel', DaAssetsPanel);
