/* eslint-disable no-underscore-dangle */
// Stage 4 "Pre-flight check" panel (ticket #43).
//
// The right-hand card of Stage 4: it scores the generated page. Once the page
// exists (it carries a `previewUrl`), the panel auto-runs two audits in
// parallel - preflight-contracts.js `runPsiAudit` for Web performance /
// Accessibility / SEO / Best practices (keyed with `readPsiKey`, else the
// keyless quota answers 429) and `assessPage` for LLM visibility / Engagement &
// conversion - rolls the category scores up with `rollupReadiness`, and shows
// the demo's "Running audit..." -> "NN% readiness" progression. Each category
// is a row with its passed/total, a pass check, and an expandable detail.
// "Refresh" re-runs both audits.
//
// The results are persisted with stage-state.js `savePreflight` (which merges,
// so a concurrent write is not clobbered) and announced with `preflight-changed`
// so the shell keeps its cache. Wiring the panel into the shell and the Stage
// 4 -> 5 gate is a follow-up (#44).
//
// The panel never blocks: both audit seams return a soft `{error}` instead of
// throwing, so a failed audit only degrades its categories to an "unavailable"
// row - exactly how brief-panel.js treats a failed brief. With no generated
// page the panel sits in a neutral idle state.

import { LitElement, html } from 'da-lit';
import {
  readPsiKey, runPsiAudit, assessPage, rollupReadiness,
} from './preflight-contracts.js';
import { savePreflight } from './stage-state.js';
import {
  auditUrl, measuredCategories, displayRows, categoryState, rowCount, rowDetail,
  readinessLabel, readinessNote, preflightChanges,
} from './preflight-logic.js';

const STATE_MARKS = { pass: '\u2713', attention: '!', unavailable: '\u2013' };

// One category: a pass check, the name, passed/total, and an expandable detail
// (a <details> so the disclosure is keyboard accessible for free).
function renderRow(row) {
  const state = categoryState(row);
  const count = rowCount(row);
  return html`
    <details class="cw-pf-row is-${state}">
      <summary class="cw-pf-summary">
        <span class="cw-pf-mark" aria-hidden="true">${STATE_MARKS[state]}</span>
        <span class="cw-pf-name">${row.name}</span>
        <span class="cw-pf-count">${count || 'Unavailable'}</span>
      </summary>
      <p class="cw-pf-detail">${rowDetail(row)}</p>
    </details>`;
}

class DaPreflightPanel extends LitElement {
  static properties = {
    context: { attribute: false },
    daFetch: { attribute: false },
    slug: { attribute: false },
    brief: { attribute: false },
    page: { attribute: false },
    preflight: { attribute: false },
    _rows: { state: true },
    _measured: { state: true },
    _ranAt: { state: true },
    _running: { state: true },
    _error: { state: true },
  };

  constructor() {
    super();
    this.context = null;
    this.daFetch = null;
    this.slug = null;
    this.brief = null;
    this.page = null;
    this.preflight = null;
    this._rows = [];
    this._measured = [];
    this._ranAt = '';
    this._running = false;
    this._error = null;
  }

  createRenderRoot() {
    return this;
  }

  firstUpdated() {
    const saved = this.preflight?.categories ?? [];
    this._measured = saved;
    this._rows = saved;
    this._ranAt = this.preflight?.ranAt || '';
    // Auto-run only once the page exists and nothing has run yet; a saved run
    // opens as-is and "Refresh" re-runs it.
    this.maybeRun();
  }

  // The page is generated by its sibling panel, so it can arrive after this one
  // is on screen: audit as soon as a preview URL shows up.
  updated(changed) {
    if (changed.has('page')) this.maybeRun();
  }

  maybeRun() {
    if (auditUrl(this.page) && !this._rows.length && !this._running) this.run();
  }

  // Both audits run in parallel and neither throws: a failure comes back as a
  // soft `{error}`, which becomes an "unavailable" row for that source's
  // categories. The PSI key comes from the DA config sheet - without it the
  // keyless quota answers 429.
  async run() {
    const url = auditUrl(this.page);
    if (!url || this._running) return;
    this._running = true;
    this._error = null;
    try {
      const apiKey = await readPsiKey(this.context, this.daFetch);
      const [psi, ao] = await Promise.all([
        runPsiAudit(url, { apiKey }),
        assessPage(this.context, this.brief, this.page),
      ]);
      this._measured = measuredCategories(psi, ao);
      this._rows = displayRows(psi, ao);
      this._ranAt = new Date().toISOString();
      await this.persist();
    } finally {
      this._running = false;
    }
  }

  // Persist through savePreflight so the pre-flight record merges into the
  // project record rather than clobbering it, then tell the shell what changed.
  async persist() {
    if (!this._measured.length) return;
    try {
      const changes = preflightChanges(this._measured, this._ranAt);
      const preflight = await savePreflight(this.context, this.daFetch, this.slug, changes);
      this.preflight = preflight;
      this.dispatchEvent(new CustomEvent('preflight-changed', {
        detail: { preflight }, bubbles: true, composed: true,
      }));
    } catch (e) {
      this._error = `The audit ran, but saving it failed: ${e.message || 'unknown error'}`;
    }
  }

  get phase() {
    if (this._running) return 'running';
    return this._rows.length ? 'done' : 'idle';
  }

  renderStatus() {
    const { phase } = this;
    const readiness = rollupReadiness(this._measured);
    const width = phase === 'done' ? `${readiness}%` : '100%';
    return html`
      <div class="cw-pf-status">
        <p class="cw-pf-readiness">${readinessLabel(phase, readiness)}</p>
        <div class="cw-pf-bar ${phase === 'running' ? 'is-running' : ''}"
          role="progressbar" aria-label="Page readiness"
          aria-valuenow=${phase === 'done' ? readiness : 0}
          aria-valuemin="0" aria-valuemax="100">
          <span class="cw-pf-bar-fill" style="width:${width};"></span>
        </div>
        <p class="cw-pf-note cw-muted">${readinessNote(phase, this._rows)}</p>
      </div>`;
  }

  renderRows() {
    if (this._running && !this._rows.length) {
      return html`<p class="cw-muted">Running audit...</p>`;
    }
    if (!this._rows.length) {
      return html`<p class="cw-muted">
        No page yet. The pre-flight check runs once the page is generated.</p>`;
    }
    return html`<div class="cw-pf-rows">${this._rows.map(renderRow)}</div>`;
  }

  render() {
    return html`
      <div class="cw-cn-header">
        <h3 class="cw-kw-title">Pre-flight check</h3>
        <button class="nx-action-btn nx-btn-sm"
          ?disabled=${this._running || !auditUrl(this.page)}
          @click=${() => this.run()}>Refresh</button>
      </div>
      <p class="cw-kw-label">Assessing page readiness</p>
      ${this.renderStatus()}
      ${this.renderRows()}
      ${this._error ? html`<p class="cw-error">${this._error}</p>` : ''}`;
  }
}

customElements.define('da-preflight-panel', DaPreflightPanel);
